name: review

on:
  pull_request:

jobs:
  prh:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build prh
        uses: docker/build-push-action@v2
        with:
          file: prh/Dockerfile
          tags: prh
          push: false
      - name: install reviewdog
        run: >
          GITHUB_URL=https://raw.githubusercontent.com/reviewdog/reviewdog &&
          INSTALL_URL=${GITHUB_URL}/master/install.sh &&
          wget -O - -q ${INSTALL_URL} | sh -s
      - name: run prh
        uses: addnab/docker-run-action@v3
        with:
          image: prh
          options: -v ${{ github.workspace }}:/work
          run: REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} sh .github/workflows/scripts/prh.sh

  textlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build textlint
        uses: docker/build-push-action@v2
        with:
          file: textlint/Dockerfile
          tags: textlint
          push: false
      - name: install reviewdog
        run: >
          GITHUB_URL=https://raw.githubusercontent.com/reviewdog/reviewdog &&
          INSTALL_URL=${GITHUB_URL}/master/install.sh &&
          wget -O - -q ${INSTALL_URL} | sh -s
      - name: run textlint
        uses: addnab/docker-run-action@v3
        with:
          image: textlint
          options: -v ${{ github.workspace }}:/work
          run: REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} sh .github/workflows/scripts/textlint.sh
